stages:
  - ynov_b3
  - lint

b3_echo_hello:
  stage: ynov_b3
  image: alpine # là
  script:
    - cat /etc/os-release

lint-yaml:
  stage: lint
  image:
    name: cytopia/yamllint
    entrypoint: ["/bin/ash", "-c"]
  script:
    - yamllint -f colored .
