- name: Create webroot
  file:
    path: "{{ item.nginx_webroot }}"
    state: directory
  with_items: '{{ add_vhosts }}'

- name: Create index
  copy:
    dest: "{{ item.nginx_webroot }}/index.html"
    content: "{{ item.nginx_index_content }}"
  with_items: '{{ add_vhosts }}'

- name: NGINX Virtual Host
  template:
    src: vhost.conf.j2
    dest: /etc/nginx/conf.d/{{ item.nginx_servername }}.conf
  with_items: '{{ add_vhosts }}'
