- name: Remove webroot
  file:
    path: "{{ item.nginx_webroot }}"
    state: absent
  with_items: '{{ remove_vhosts }}'

- name: Remove index
  file:
    path: "{{ item.nginx_webroot }}/index.html"
    state: absent
  with_items: '{{ remove_vhosts }}'

- name: Remove NGINX Virtual Host
  file: 
    path: /etc/nginx/conf.d/{{ item.nginx_servername }}.conf
    state: absent
  with_items: '{{ remove_vhosts }}'
