# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.env.enable
  config.vbguest.auto_update = false
  config.vm.box_check_update = false

  config.vm.box = "focal-server-cloudimg-amd64-vagrant"
  config.vm.box_url = "https://cloud-images.ubuntu.com/focal/current/focal-server-cloudimg-amd64-vagrant.box"

  config.ssh.forward_agent = true

  config.vm.provision "shell", path: "setup.sh"

  # Config une première VM "node1.tp2.cloud"
  config.vm.define "node1.tp2.cloud" do |node1|
    node1.vm.network "private_network", ip: "192.168.56.4"
    node1.vm.hostname = "node1.tp2.cloud"
    node1.vm.cloud_init do |cloud_init|
      cloud_init.content_type = "text/cloud-config"
      cloud_init.path = "cloud-init-node.yml"
    end
  end

end
