Vagrant.configure("2") do |config|
  config.env.enable
  config.vbguest.auto_update = false
  config.vm.box_check_update = false

  config.vm.define "ubuntu-cloud-init"
  config.vm.box = "focal-server-cloudimg-amd64-vagrant"
  config.vm.box_url = "https://cloud-images.ubuntu.com/focal/current/focal-server-cloudimg-amd64-vagrant.box"

  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "private_network", ip: "192.168.56.2"
  config.ssh.forward_agent = true
  
  config.vm.provider "virtualbox" do |v|
    v.name = "ubuntu-cloud-init"
  end
 
#  config.vm.provision "shell", path: "setup.sh"
 
  config.vm.cloud_init do |cloud_init|
    cloud_init.content_type = "text/cloud-config"
    cloud_init.path = "data.yml"
  end

end

